import os
import re
import urlparse
import shutil
import zlib
import json
from datetime import datetime, timedelta
try:
    import cPickle as pickle
except ImportError:
    import pickle
from link_crawler import link_crawler


class DiskCache:
    """
    Dictionary interface that stores cached 
    values in the file system rather than in memory.
    The file path is formed from an md5 hash of the key.

    >>> cache = DiskCache()
    >>> url = 'http://example.webscraping.com'
    >>> result = {'html': '...'}
    >>> cache[url] = result
    >>> cache[url]['html'] == result['html']
    True
    >>> cache = DiskCache(expires=timedelta())
    >>> cache[url] = result
    >>> cache[url]
    Traceback (most recent call last):
     ...
    KeyError: 'http://example.webscraping.com has expired'
    >>> cache.clear()
    """
    """
	This is none pickle version of cache. The file generated by pickle version can't be read directly
	by narmal editor. That is the main reason to create this none-pickle version cache.
	edit by jun on 08/04/2016.
    """
    def __init__(self, cache_dir='cache', expires=timedelta(days=30), compress=False):
        """
        cache_dir: the root level folder for the cache
        expires: timedelta of amount of time before a cache entry is considered expired
        compress: whether to compress data in the cache
        """
        self.cache_dir = cache_dir
        self.expires = expires
        self.compress = compress

    
    def __getitem__(self, url):
        """Load data from disk for this URL
        """
        path = self.url_to_path(url)
        if os.path.exists(path):
            #extract info from file, and convert timestamp from string into utcnow format
	    #[data,timestamp]=json.load(file(path))
	    #with encoding='gbk' can solve most of chinese website problems
	    try:
	        json_dict=json.load(file(path))[0]
	    except:
	        json_dict=json.load(file(path),encoding='gbk')[0]

	    data = json_dict['data']
	    timestamp = json_dict['timestamp']
	    timestamp = datetime.strptime(timestamp,'%Y-%m-%d %H:%M:%S.%f')
	    result = data
            
            if self.has_expired(timestamp):
                raise KeyError(url + ' has expired')
            return result
        else:
            # URL has not yet been cached
            raise KeyError(url + ' does not exist')


    def __setitem__(self, url, result):
        """Save data to disk for this url
        """
        path = self.url_to_path(url)
        folder = os.path.dirname(path)
        if not os.path.exists(folder):
            os.makedirs(folder)

        #using json to store data into file. Add utcnow to the data to judge the file is expired
	#json can only take string as input, that is why convert utcnow into string
        data=result
	data = [{'data':data,'timestamp':str(datetime.utcnow())}]
	#data = [data,str(datetime.utcnow())]
        json.dump(data,file(path,'w'),ensure_ascii=False)


    def __delitem__(self, url):
        """Remove the value at this key and any empty parent sub-directories
        """
        path = self._key_path(url)
        try:
            os.remove(path)
            os.removedirs(os.path.dirname(path))
        except OSError:
            pass


    def url_to_path(self, url):
        """Create file system path for this URL
        """
        components = urlparse.urlsplit(url)
        # when empty path set to /index.html
        path = components.path
        if not path:
            path = '/index.html'
        elif path.endswith('/'):
            path += 'index.html'
        filename = components.netloc + path + components.query
        # replace invalid characters
        filename = re.sub('[^/0-9a-zA-Z\-.,;_ ]', '_', filename)
        # restrict maximum number of characters
        filename = '/'.join(segment[:255] for segment in filename.split('/'))
        return os.path.join(self.cache_dir, filename)


    def has_expired(self, timestamp):
        """Return whether this timestamp has expired
        """
        return datetime.utcnow() > timestamp + self.expires


    def clear(self):
        """Remove all the cached values
        """
        if os.path.exists(self.cache_dir):
            shutil.rmtree(self.cache_dir)



if __name__ == '__main__':
    link_crawler('http://example.webscraping.com/', '/(index|view)', cache=DiskCache())
